### ISSUE TITLE
Issue 1 - User can see the home page, click in to see all national parks, and click those parks to view information

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/front-end-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the home page, click in to see all national parks, and click those parks to view information

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will see the hero page, then click into the view that shows them all the national parks. They can scroll through and click into any park, which takes them to an info page about the Park. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2024-03-05 at 4 31 38 PM](https://github.com/nmotamedi/front-end-project/assets/144378279/9c69aa4a-7d39-4f0e-82e1-5f7c42059d82)
![Screen Shot 2024-03-05 at 4 31 29 PM](https://github.com/nmotamedi/front-end-project/assets/144378279/48603582-2ed0-48b4-8de8-aae0e02e4fbc)
![Screen Shot 2024-03-05 at 4 31 11 PM](https://github.com/nmotamedi/front-end-project/assets/144378279/0ca1f9b4-149b-46d8-8040-97fce8edf7af)
![Screen Shot 2024-03-05 at 4 30 47 PM](https://github.com/nmotamedi/front-end-project/assets/144378279/8842141d-8d59-47a8-aaf8-8057bc2d855a)
![Screen Shot 2024-03-05 at 4 30 27 PM](https://github.com/nmotamedi/front-end-project/assets/144378279/17346005-392b-4ff5-b7ec-5f671d1ffdaa)
![Screen Shot 2024-03-05 at 4 30 10 PM](https://github.com/nmotamedi/front-end-project/assets/144378279/9901441f-48fa-4d67-9303-6ff586aa3a25)
<img width="1187" alt="Screen Shot 2024-03-05 at 8 23 43 AM" src="https://github.com/nmotamedi/front-end-project/assets/144378279/9cdcc09d-4607-4a3c-8f53-a9e4cf0b9cc0">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML for the hero page
- [x] CSS for Hero Page
- [x] Create the HTML for the main list page with a hidden class
- [x] CSS for the list page 
- [x] #9
- [x] CSS for the park info page
- [x] Add hidden CSS to the layout.css
- [x] Add TS to main.ts to pull parks list from NPS API and clean data for the main list. 
- [x] Create DOM Tree on hidden main list with parks, imgs from API url, states from API addresses. 
- [x] Add event listener to the home button that will switch views back to main list. 
   - [x] Maybe make a view swap function
- [x] Add event listeners to main.ts to take users from the hero page to the main list 
   - [x] Query the dom for the hero button
   - [x] Add class of hidden to the hero page and remove class of hidden from the main list. 
- [x] Add event listeners to main.ts to take users to the park info page if a park is clicked. 
   - [x] Find the target that was clicked and use that information to find the specific park information from the API JSON. 
   - [x] Populate the HTML with information pulled from the JSON.
   - [x] Add class of hidden to the main list and remove class of hidden from the detail page. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Check if there is any code that can be simplified by creating a function. 
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
