### ISSUE TITLE
Issue 5 - Put a loading screen while grabbing events from API

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/front-end-project#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will see a loading screen with a pinwheel while we are contacting the API and getting events.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user puts in their Travel start and end date, a modal will open with a pinwheel that will close when the events are received. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="723" alt="Screen Shot 2024-03-11 at 12 34 44 PM" src="https://github.com/nmotamedi/front-end-project/assets/144378279/dab24172-7e6d-4b98-93fc-6adb79adafb0">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add modal HTML
- [x] Open modal TS on the date end 
- [x] Close modal TS at the end of the async function. 
- [x] Display No Events if no events received from the API.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
