### ISSUE TITLE
Bug: Add button to change a wishlist park to a visited park, button to edit/remove travel plans.

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/front-end-project#16]
#### Desired Behavior

> ##### The app should ...

Allow the user to edit their travel plans, delete travel plans, and transition a park from travel plan to visited. 

#### Actual Behavior

> ##### The app does this instead ...

Once a park is in wishlist, there is no way to switch, edit or delete. 

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

Add a park to wishlist. 

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Remove piece of code that hides the Add to Journal Button
- [x] Change the way the forms are queried to change the park status to Visited. 
- [x] Add button to edit travel plans from info page 
   - [x] Populate form with data.park information. 
      - [x] Activities
      - [x] Dates
      - [x] Events
   - [x] Add delete button to remove travel plans if editing. 
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
