### ISSUE TITLE
Issue 2 - User can catalog which parks they visited and view them in a separate list.

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/front-end-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can catalog which parks they visited and view them in a separate list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once a user is on a park page they have not been to before, they can click a button to change views into a form page where they can input information about when they visited the park and what activities they did. Once they submit the form, the park information page is populated with new information. A new view option is also available in which the user can view only parks visited. On the main list, any park visited will have a book icon next to it. Data.ts will be updated with a visit object to remember the visit. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2024-03-05 at 5 03 41 PM](https://github.com/nmotamedi/front-end-project/assets/144378279/a069170b-bffc-48bd-a684-98cd08201ebc)
![Screen Shot 2024-03-05 at 5 03 34 PM](https://github.com/nmotamedi/front-end-project/assets/144378279/7215121a-097c-4056-aad1-3e1394fe863a)
![Screen Shot 2024-03-05 at 5 03 26 PM](https://github.com/nmotamedi/front-end-project/assets/144378279/4f5c4d3a-e2f1-49fe-91eb-15b6215f96ab)
![Screen Shot 2024-03-05 at 5 03 20 PM](https://github.com/nmotamedi/front-end-project/assets/144378279/0a7a4617-5d32-4a3d-a1dc-cb7d45dde388)
![Screen Shot 2024-03-05 at 5 03 12 PM](https://github.com/nmotamedi/front-end-project/assets/144378279/0cf87989-737d-4ecc-b0dd-fefab047f5d8)
![Screen Shot 2024-03-05 at 5 03 06 PM](https://github.com/nmotamedi/front-end-project/assets/144378279/598893ef-9f76-4ed5-acd0-cbacaf69ea52)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update Data.ts to save to local storage and check for saved data in local storage. 
- [x] Move create empty Parks array to Data.ts and only set it if local storage is empty. 
- [x] Add a park count variable to Data.ts that increments with every park visited (2 for Sequoia). 
- [x] Add optional properties to National Parks interface for Status, Dates Visited, Activities done, Dates to Visit, Activities to Do, Events to Do.
- [x] Create new view on HTML under park information header with a form entry with Dates Visited, Hikes done, Activities done. 
- [x] Add event listener to 'Add to Journal' button. 
   - [x] Switch view from info page to form page. 
   - [x] Populate Activities select options with parks activities array elements. 
- [x] Add event listener to Form submit button that updates the park being edited with the information from the form. Increment parkCount. 
- [x] Get activities selected.
- [x] View, current index, current park, etc reset
- [x] Update the HTML for Park Info page to include hidden sections for Dates Visited, Dates to Visit, Activities Done, Activities to Do, and Events to Do. 
- [x] Update the event listener that takes the user to the park page that first checks the Status property and populates the appropriate page elements. 
- [x] Figure out map.
- [x] Add Journal FontAwesome to the All Parks list next to parks visited. 
- [x] Add event listener to the journal icon on Hero and Header page that:
   - [x] Populates the list with only parks from the NPArray with a status of visited. 
   - [x] Change the Text Content of the page title to Park Journal. 
   - [x] Add hidden HTML and update text content with `${current score}/63` and unhide 
- [x] Update async function to move the population of the list to the event listener. 
- [x] Update CSS
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
