### ISSUE TITLE
Issue 3 - User can create wishlists for their next parks and view them in a separate list. 

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/front-end-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create wishlists for their next parks and view them in a separate list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once a user is on a park page they have not been to before, they can click a button to change views into a form page where they can input information about when they want to visit the park and what activities they want to do. The dates they input will also populate a selection menu with events during the window. Once they submit the form, the park information page is populated with new information. A new view option is also available in which the user can view only parks on the wishlist. On the main list, any park visited will have a pencil icon next to it. Data.ts will be updated with a wish object to remember the wish.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2024-03-05 at 5 09 22 PM](https://github.com/nmotamedi/front-end-project/assets/144378279/dcd21b6b-78e5-4e6b-86ae-a96954646be0)
![Screen Shot 2024-03-05 at 5 09 15 PM](https://github.com/nmotamedi/front-end-project/assets/144378279/34232a1b-6407-42ca-a44e-ddd39dd623cf)
![Screen Shot 2024-03-05 at 5 09 08 PM](https://github.com/nmotamedi/front-end-project/assets/144378279/4ac70d25-f0a1-4ce4-a6b4-f95b5d5b57cb)
![Screen Shot 2024-03-05 at 5 09 03 PM](https://github.com/nmotamedi/front-end-project/assets/144378279/e78934c5-45cc-43af-a735-7eb817c77d04)
![Screen Shot 2024-03-05 at 5 08 55 PM](https://github.com/nmotamedi/front-end-project/assets/144378279/bac4db93-2872-4e0f-a081-1fad980fda9b)
![Screen Shot 2024-03-05 at 5 08 50 PM](https://github.com/nmotamedi/front-end-project/assets/144378279/52169365-1ba6-4ec9-a993-6232c90e9e58)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update event listener to $infoButtons to take user to wishlist form.. 
   - [x] Change currentStatus to Wishlist
   - [x] Populate activities options with activities from park.activities
   - [x] Create and call async function for the below:
      - [x] Get ThingsToDo and Events information from API
      - [x] Populate events options with ThingsToDo and Events
- [x] Add view type to view swapper, 'wishlist-form' that:
   - [x] Unhides all the form elements 
   - [x] Hides the buttons
   - [x] Change text content to Wishlist text. 
   - [x] Change min dates for start date to today[0].   
- [x] Add view type to view swapper, 'wishlist-view' that:
   - [x] Changes the viewlist title to "Travel Plans"
   - [x] Populates list only with status: 'wishlist'.
- [x] Add event listener to change min end date to start date input. 
- [x] Add section to submit event listener to get correct data and put it into object. 
   - [x] If wishlist - change view to wishlist list
   - [x] If visited - change view to visited list 
- [x] Add event listener with viewSwapper('wishlist-view') to hero wishlist button and header.
- [x] Add section to populate function to add the pencil icon for wishlist parks. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
